@RpcServer_HostAddress = http://localhost:5209

GET {{RpcServer_HostAddress}}/
Accept: application/json

###
POST {{RpcServer_HostAddress}}/rpc-batch/
Accept: application/json

[
    {
        "Seq": 0,
        "Method": "benchmark-hello",
        "ArgDict": { "Name": "Jaru" }
    }
]
###